api:
  spec:
    file: swagger.yaml
    icon: favicon.ico
    path: apidoc
    version: v1
  name: Watchmen Project
  desc: internal monitoring systems...
  host: 0.0.0.0
  port: 8080
  path: api
  enable_ssl: false
  cert_key: apidoc/cert.key
  cert_pem: apidoc/cert.pem
  timeout: 30
  version: 1.0.0
  debug: true

aws:
  environment: test
  s3:
    bucket: cyber-intel-test
    prefix: watchmen

debug:
  # CRITICAL/FATAL = 50, ERROR = 40, WARNING/WARN = 30, INFO = 20, DEBUG = 10
  level: 20

env: dev

mysql:
  database:
  host:
  port: 3306
  username: admin
  password:

ecs:
  feeds:
    cluster: cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8
    url: https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8/services

holiday:
  good_friday: false
  day_b4_xmas_eve: true

jupiter:
  enable_calendar: true
  endpoints: jupiter/endpoints.json
  sns_topic: arn:aws:sns:us-east-1:405093580753:Sockeye
  s3_prefix: jupiter
  min_items: 1
  hr_start_pdt: 6
  hr_end_pdt: 18

logging:
  level: 10

manhattan:
  sns_topic: arn:aws:sns:us-east-1:405093580753:cyberintel-feeds-prod

moloch:
  sns_topic: arn:aws:sns:us-east-1:405093580753:cyberintel-feeds-prod

ozymandias:
  sns_topic: arn:aws:sns:us-east-1:405093580753:Hancock

rorschach:
  sns_topic: arn:aws:sns:us-east-1:405093580753:Hancock

silhouette:
  sns_topic: arn:aws:sns:us-east-1:405093580753:cyberintel-lookalike-s3

spectre:
  sns_topic: arn:aws:sns:us-east-1:405093580753:Hancock

sns:
  pager: arn:aws:sns:us-east-1:405093580753:PagerDuty
