debug:
  # CRITICAL/FATAL = 50, ERROR = 40, WARNING/WARN = 30, INFO = 20, DEBUG = 10
  level: 20

mysql:
  database:
  host:
  port: 3306
  username: admin
  password:

api:
  timeout: 7

bernard:
  json_file: emr_clusters_to_check.json
  s3_bucket: cyber-intel-test
  s3_prefix: watchmen/bernard
  hour_threshold: 12

comedian:
  domaintools_api_key: AQICAHgBtb0SZhoZJa0NRdEJtBKhwIPnNwIJwKkl1vAEW6J5QQFX8KbGeiR7/8wXuQsCpyPEAAAAezB5BgkqhkiG9w0BBwagbDBqAgEAMGUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMncCU650SquoypWNCAgEQgDhU4rx80yjG8hcwQCa4vz6OsrVH6VmHWVY1IEx8y5NoWO6DOFws5YCnC9OZ/ZqiG1k1co52ifEoGA==
  virustotal_api_key: AQICAHiWWK54vE77SA6IjYZJ/ttX+qO2oK2rkuGMvS+t7o+vygHkO7QLSjRHQP6cQnRK9GUkAAAAojCBnwYJKoZIhvcNAQcGoIGRMIGOAgEAMIGIBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDFx06wSdcdQ3wHjbEgIBEIBbMiwUqYUOU31l84vhEEanSVri8Jk+BrRGJgfuh0njdR8CIDVN+iv7B8wSGuSWkzZPYSe7RBu9IVakPsYEFyiXSRGDGWj5N2fWeTdh2A37ZegX+o9RiPioxQQ6PA==

ecs:
  feeds:
    cluster: cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8
    url: https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8/services

emr:
  clusters_url: https://console.aws.amazon.com/elasticmapreduce/home?region=us-east-1#cluster-list 
    
holiday:
  good_friday: false
  day_before_xmas_eve: false
  thursday_before_independence_day: false
  friday_before_independence_day: true
  spring_break_day_bool: true
  spring_break_month: 4
  spring_break_day: 2

jupiter:
  bucket: cyber-intel-test
  endpoints: endpoints.json
  sns_topic: arn:aws:sns:us-east-1:405093580753:Watchmen_Test
  s3_prefix: watchmen/jupiter

logging:
  level: 10

manhattan:
  json_file: feeds_to_check.json
  log_group_name: feed-eaters-prod
  table_name: CyberInt-Reaper-prod-DynamoDbStack-3XBEIHSJPHBT-ReaperMetricsTable-1LHW3I46AEDQJ
  sns_topic: arn:aws:sns:us-east-1:405093580753:Watchmen_Test
  s3_bucket: cyber-intel-test
  s3_prefix: watchmen/manhattan

metropolis:
  bucket_name: cyber-intel
  path_prefix: analytics/change_detection/prod/
  data_file: watchmenResults.csv
  reaper:
    metrics_url: https://1niw6imbal.execute-api.us-east-1.amazonaws.com/prod/query_metrics?time=day
    metrics_api_key: AQICAHg3HNyIwRj/VgA+LeTSbBvD+KLqwR4I7fTUIoefURORLQH2QRUYgyk9DP/rcj5pWJnrAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDHiRxI65Zw2R+6esvgIBEIBD4F2NpEz3teCoknvVBJxJU4R82Oe3X8ZVINUuXh0Co2GsZlymc8p4aA2Z3En3QCk1qxomQJKXqSqsQ2aQQtoqepa3ww==

mothman:
  bucket_name: cyber-intel
  path_prefix: malspam
  mail_sources: forevermail,uscert

niteowl:
  github_token: AQICAHjgFSn/OLf0nqRgxqYgtITXps0RY6ItQKkRvwzM+g5SDgGRNZGrXzngBY20SwTA4gmEAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDK7+T+li2pbrdzsCnAIBEIBDl0k617ys75djRoYyvMTrkv8W1SGUg37k58zPHcxQIdVWXp/AjY77cQZQfd0FeVDn7TdNy+Qr1zVBDkYB3+o2NSWV3Q==
  targets: github_targets.yaml

result_svc:
  default: arn:aws:sns:{region}:{account_id}:WatchmenTest
  atg: arn:aws:sns:{region}:{account_id}:Watchmen_Test
  cyberintel: arn:aws:sns:{region}:{account_id}:WatchmenTest
  saas: arn:aws:sns:{region}:{account_id}:WatchmenTest

storage_service:
  s3_prefix: watchmen/results/{}/{}/{}/{}.json

silhouette:
  bucket_name: cyber-intel
  path_prefix: analytics/lookalike2/prod/status/
  sns_topic: arn:aws:sns:us-east-1:405093580753:Watchmen_Test

slater:
  api_key: AQICAHgBtb0SZhoZJa0NRdEJtBKhwIPnNwIJwKkl1vAEW6J5QQFX8KbGeiR7/8wXuQsCpyPEAAAAezB5BgkqhkiG9w0BBwagbDBqAgEAMGUGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMncCU650SquoypWNCAgEQgDhU4rx80yjG8hcwQCa4vz6OsrVH6VmHWVY1IEx8y5NoWO6DOFws5YCnC9OZ/ZqiG1k1co52ifEoGA==
  host: api.domaintools.com
  uri: /v1/account
  api_username: IID_dev
  threshold_start: 50

spectre:
  bucket_name: cyber-intel
  path_prefix: hancock/georgia_tech/
  sns_topic: arn:aws:sns:us-east-1:405093580753:Watchmen_Test

sns:
  pager: arn:aws:sns:us-east-1:405093580753:PagerDuty
