api:
  timeout: 7

aws:
  s3:
    bucket: cyber-intel-test
    prefix: watchmen

holiday:
  good_friday: false
  day_b4_xmas_eve: true

jupiter:
  endpoints: jupiter/endpoints.json
  sns_topic: arn:aws:sns:us-east-1:405093580753:Sockeye
  min_items: 1

ecs:
  feeds:
    cluster: cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8
    url: https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/cyberint-feed-eaters-prod-EcsCluster-L94N32MQ0KU8/services

sns:
  pager: arn:aws:sns:us-east-1:405093580753:PagerDuty
