---
  version: 1
  disable_existing_loggers: False
  formatters:
    complex:
      format: "%(asctime)s [%(name)s/%(module)s #%(lineno)d] %(levelname)s: %(message)s"
    console:
      format: "%(asctime)s [%(name)s/%(module)s #%(lineno)d] %(levelname)s: %(message)s"
    custom:
      (): watchmen.utils.logger_formatter.factory
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: custom
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: complex
      filename: watchmen.log
      maxBytes: 10485760 # 10MB
      backupCount: 5
      encoding: utf8
  loggers:
    root:
      handlers: [console, file]
      level: DEBUG
    watchmen:
      handlers: [console, file]
      level: DEBUG
      qualname: watchmen
      propagate: 0
