version: "3.7"

services:

    watchmen:
      image: infobloxcto/watchmen
      build: Dockerfile.prod
      hostname: watchmen
      container_name: watchmen
      command: ["/bin/bash", "-c", "make run-api"]
      environment:
        - API_PORT
        - AWS_DEFAULT_REGION
        - AWS_SECRET_ACCESS_KEY
        - AWS_ACCESS_KEY_ID
      network_mode: bridge
      privileged: true
      expose:
        - 8080
      ports:
        - 0.0.0.0:8080:8080
      restart: always
      volumes:
        - type: bind
          source: ./
          target: /src/cyberint-watchmen/

volumes:
  dir-svc:
