Hourly:

- target_name: Poseidon Heka Data - LZ
  items:
  - bucket_name: ib-dl-lz-ttl-prod
    prefix: ib-dl-saas-lz-prod/heka/year=%0Y/month=%0m/day=%0d/
    suffix: .gz

- target_name: Poseidon Heka Data - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: heka/year=%0Y/month=%0m/day=%0d/
    suffix: .json.gz

- target_name: Newly Observed Data
  items:
  - bucket_name: deteque-new-observable-data
    full_path: NewlyObserved{var}/%Y/%-m/%-d/ZMQ_Output_%Y_%-m_%-d_%-H_
    path_vars: [Domains, Hostname]
    suffix: .txt


Daily:

- target_name: Poseidon DNS Data - LZ
  items:
  - bucket_name: ib-customer-data-usa-va
    prefix: parquet-dns/com.infoblox.300224/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet

  - bucket_name: ib-customer-data-usa-va
    prefix: parquet-northstar-dns/com.infoblox.300224/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    min_total_files: 0
    min_total_size_kb: 0

- target_name: Poseidon DNS Data - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: dns-logs/customer/year=%0Y/month=%0m/day=%0d/storage_id=300224/
    suffix: .parquet

  - bucket_name: ib-dl-saas-cz-prod
    prefix: dns-logs/farsight/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    max_items: 100

- target_name: Poseidon DNS Customer Data - RZ
  items:
  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/metadata/year=%0Y/month=%0m/day=%0d/storage_id=300224/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/name_servers/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/qtype_answer_counts/qtype=1/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/query_counts/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/subdomain_counts_by_sld/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/subdomain_counts_by_source/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

- target_name: Poseidon DNS Farsight Data - RZ
  items:
  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/farsight/metadata/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/farsight/summaries/name_servers/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/farsight/summaries/qtype_answer_counts/qtype=1/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/farsight/summaries/query_counts/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']
    
  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/farsight/summaries/subdomain_counts_by_sld/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

- target_name: SaaS Apps Customer Data Phase 1 - LZ
  items:
  - bucket_name: ib-dl-saas-lz-dev-tmp
    prefix: saas-customer-data/year=%0Y/month=%0m/day=%0d/
    suffix: .json
    min_total_files: 2

- target_name: SaaS Apps Customer Data Phase 2 - LZ
  items:
  - bucket_name: ib-dl-saas-lz-prod
    path_vars: [roaming_clients, roaming_client_groups, security_policies]
    prefix: athena-full-exports/atcapi/year=%0Y/month=%0m/day=%0d/atcapi_user/{var}/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    path_vars: [accounts, sfdccsps, provision_history, ip_spaces, on_prem_applications]
    prefix: athena-full-exports/identity/year=%0Y/month=%0m/day=%0d/public/{var}/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

- target_name: SaaS Apps Customer Data Phase 1 - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: saas-customer-data/year=%0Y/month=%0m/day=%0d/
    suffix: .csv
    min_total_files: 2

- target_name: SaaS Apps Customer Data Phase 2 - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: athena-full-exports/year=%0Y/month=%0m/day=%0d/
    suffix: .csv
    min_total_files: 3

- target_name: Prometheus - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: prometheus/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    min_total_files: 0

Minutely:

  - target_name: Prometheus - LZ
    items:
    - bucket_name: ib-dl-lz-ttl-prod
      prefix: ib-dl-saas-lz-prod/prometheus/metrics-prd-1/year=%0Y/month=%0m/day=%0d/
      suffix: .json.gz
      time_offset: 30
      min_total_files: 210

