Hourly:
- target_name: Farsight Data
  items:
  - bucket_name: bitaa
    prefix: parquet/com.farsightsecurity.300021/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    time_offset: 1

Daily:
- target_name: Domain Counts Metrics
  items:
    - bucket_name: cyber-intel
      prefix: domain-counts/src=farsight/year=%0Y/month=%0m/day=%0d/
      suffix: .parquet
      whitelist: ['_SUCCESS']
    - bucket_name: cyber-intel
      prefix: domain-counts/src=customer/year=%0Y/month=%0m/day=%0d/
      suffix: .parquet
      whitelist: ['_SUCCESS']

- target_name: DS Summaries
  items:
  - bucket_name: cyber-intel
    prefix: summaries/ns_summaries/src=farsight/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

- target_name: Georgia Tech S3
  items:
    - bucket_name: cyber-intel
      full_path: hancock/georgia_tech/%0Y/%0m/gt_mpdns_%Y%m%d.zip
      time_offset: 1