Minutely:
  '00':
    - target_name: Threatwave
      items:
        - bucket_name: cyber-intel-threatwave
          prefix : '%0Y/%0m/%0d/'
          suffix : .gz
          time_offset : 10
          min_total_files : 1
