Minutely:
  '00':
    - target_name: Threatwave
      items:
        - bucket_name: cyber-intel-threatwave
          prefix : '%0Y/%0m/%0d/'
          suffix : .gz
          time_offset : 10
          min_total_files : 1

Hourly:
  '59':
    - target_name: FedPhish
      items:
      - bucket_name: cyber-intel
        full_path: malspam/fedphish/reports/year=%0Y/month=%0m/day=%0d/hour=%H/fedphishreport.json

Weekly:
  'Mon':
    '10:30':
      - target_name: Psl
        items:
          - bucket_name: cyber-intel
            full_path: analytics/enrichment-data/psl_infoblox_custom.dat
            time_offset: 1

  'Tue':
    '08:00':
      - target_name: Maxmind
        items:
          - bucket_name: cyber-intel
            prefix: maxmind/city/historic/year=%0Y/
            suffix: .tar.gz
            time_offset: 1

          - bucket_name: cyber-intel
            full_path: maxmind/city/unprocessed/year=%0Y/maxmind_geo_city.tar.gz
            time_offset: 1

          - bucket_name: cyber-intel
            prefix: maxmind/isp/historic/year=%0Y/
            suffix: .tar.gz
            time_offset: 1

          - bucket_name: cyber-intel
            full_path: maxmind/isp/unprocessed/year=%0Y/maxmind_isp.tar.gz
            time_offset: 1

  'Wed':
    '00:00':
      - target_name: MSISAC
        items:
          - bucket_name: cyber-intel
            prefix: msisac/needreview/unprocessed/year=%0Y/month=%0m/
            min_total_files: 1
