Daily:

- target_name: Poseidon DNS Data
  items:
  - bucket_name: ib-customer-data-usa-va
    prefix: parquet-dns/com.infoblox.300224/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet

  - bucket_name: ib-dl-saas-rz-prod
    prefix: dns-logs/customer/summaries/name_servers/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    whitelist: ['_SUCCESS']

- target_name: Poseidon Northstar DNS Data
  items:
  - bucket_name: ib-customer-data-usa-va
    prefix: parquet-northstar-dns/com.infoblox.300224/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    min_total_files: 0
    min_total_size_kb: 0

- target_name: SaaS Apps Customer Data Phase 1 - LZ
  items:
  - bucket_name: ib-dl-saas-lz-dev-tmp
    prefix: saas-customer-data/year=%0Y/month=%0m/day=%0d/
    suffix: .json
    min_total_files: 2

- target_name: SaaS Apps Customer Data Phase 2 - LZ
  items:
  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/atcapi/year=%0Y/month=%0m/day=%0d/atcapi_user/roaming_clients/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/atcapi/year=%0Y/month=%0m/day=%0d/atcapi_user/roaming_client_groups/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/atcapi/year=%0Y/month=%0m/day=%0d/atcapi_user/security_policies/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/identity/year=%0Y/month=%0m/day=%0d/public/accounts/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/entitlement/year=%0Y/month=%0m/day=%0d/public/sfdccsps/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/entitlement/year=%0Y/month=%0m/day=%0d/public/provision_history/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/ipam/year=%0Y/month=%0m/day=%0d/public/ip_spaces/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

  - bucket_name: ib-dl-saas-lz-prod
    prefix: athena-full-exports/hostapp/year=%0Y/month=%0m/day=%0d/public/on_prem_applications/
    suffix: .parquet
    min_total_files: 1
    min_total_size_kb: 0

- target_name: SaaS Apps Customer Data Phase 1 - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: saas-customer-data/year=%0Y/month=%0m/day=%0d/
    suffix: .csv
    min_total_files: 2

- target_name: SaaS Apps Customer Data Phase 2 - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: athena-full-exports/year=%0Y/month=%0m/day=%0d/
    suffix: .csv
    min_total_files: 3

- target_name: Prometheus - CZ
  items:
  - bucket_name: ib-dl-saas-cz-prod
    prefix: prometheus/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    min_total_files: 0

Minutely:

  - target_name: Prometheus - LZ
    items:
    - bucket_name: ib-dl-lz-ttl-prod
      prefix: ib-dl-saas-lz-prod/prometheus/metrics-prd-1/year=%0Y/month=%0m/day=%0d/
      suffix: .json.gz
      time_offset: 30
      min_total_files: 210

