Hourly:
- target_name: Farsight Data
  items:
  - bucket_name: bitaa
    prefix: parquet/com.farsightsecurity.300021/year=%0Y/month=%0m/day=%0d/
    suffix: .parquet
    # Hacky offset due to changes in Farsight processing. The monitoring process needs to be moved to where Farsight data will live from now on.
    time_offset: 24

Daily:
- target_name: Domain Counts Metrics
  items:
    - bucket_name: cyber-intel
      path_vars: [farsight, customer]
      prefix: domain-counts/src={var}/year=%0Y/month=%0m/day=%0d/
      suffix: .parquet
      whitelist: ['_SUCCESS']

- target_name: DS Summaries
  items:
    - bucket_name: cyber-intel
      prefix: summaries/ns_summaries/src=farsight/year=%0Y/month=%0m/day=%0d/
      suffix: .parquet
      whitelist: ['_SUCCESS']

- target_name: Georgia Tech S3
  items:
    - bucket_name: cyber-intel
      full_path: hancock/georgia_tech/%0Y/%0m/gt_mpdns_%Y%m%d.zip
      time_offset: 1

Weekly:
- target_name: Smartlisting
  items:
    - bucket_name: cyber-intel
      full_path: whitelist/smartlisting/prod/smartlist/src={var}/year=%Y/smartlist_%Y%m%d_{var}.csv
      offset_type: Daily
      path_vars: [atc, farsight, majestic, umbrella]
      time_offset: 1
